# 1. Используем тот же образ, что и в твоем Dockerfile
image: eclipse-temurin:21-jdk

# 2. Этапы: Сборка и Тестирование
stages:
  - build
  - test

# Кэшируем зависимости, чтобы не качать пол-интернета при каждом пуше
cache:
  paths:
    - .m2/repository

# Переменные окружения для Maven
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

# --- ЭТАП СБОРКИ ---
build_job:
  stage: build
  script:
    - chmod +x mvnw
    - ./mvnw clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

# --- ЭТАП ТЕСТОВ ---
test_job:
  stage: test
  script:
    - chmod +x mvnw
    - ./mvnw test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    paths:
      - target/site/jacoco/ # Здесь будет твой отчет по покрытию кода (Jacoco)
    expire_in: 1 week