package com.kpmg.qtracker.migration;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.init.ScriptUtils;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

class ControlStatusMigrationTest {

    @Test
    void migrationNormalizesLegacyStatuses() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:status-migration;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE control_controls (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, control_status VARCHAR(255))");
            statement.execute("CREATE TABLE workflow_steps (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status VARCHAR(255))");
            statement.execute("CREATE TABLE workflow_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, from_step VARCHAR(255), to_step VARCHAR(255))");

            statement.execute("INSERT INTO control_controls(control_status) VALUES " +
                    "('In Progress')," +
                    "('Facilitator Review')," +
                    "('Control Operator Review')," +
                    "('SoQM Lead Review')," +
                    "('Process Owner Review')," +
                    "('Returned by Control Operator')," +
                    "('Returned by SoQM Lead')," +
                    "('Returned by Process Owner')," +
                    "('Completed')," +
                    "('Reject')," +
                    "('Cancelled')");

            statement.execute("INSERT INTO workflow_steps(status) VALUES " +
                    "('NOT_STARTED')," +
                    "('FACILITATOR_REVIEW')," +
                    "('CONTROL_OPERATOR_REVIEW')," +
                    "('SOQM_LEAD_REVIEW')," +
                    "('PROCESS_OWNER_REVIEW')," +
                    "('RETURNED')," +
                    "('REJECTED')," +
                    "('COMPLETED')");

            statement.execute("INSERT INTO workflow_history(from_step, to_step) VALUES " +
                    "('Control Operator Review', 'SoQM Lead Review')," +
                    "('Returned by Control Operator', 'Facilitator Review')," +
                    "('Process Owner Review', 'Completed')");

            ScriptUtils.executeSqlScript(connection,
                    new ClassPathResource("db/migration/V1__normalize_control_statuses.sql"));

            assertThat(selectStatus(connection, "control_controls", 1, "control_status")).isEqualTo("DRAFT");
            assertThat(selectStatus(connection, "control_controls", 2, "control_status")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "control_controls", 3, "control_status")).isEqualTo("REVIEW");
            assertThat(selectStatus(connection, "control_controls", 4, "control_status")).isEqualTo("SOQM_HEAD_REVIEW");
            assertThat(selectStatus(connection, "control_controls", 5, "control_status")).isEqualTo("PROCESS_OWNER_REVIEW");
            assertThat(selectStatus(connection, "control_controls", 6, "control_status")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "control_controls", 7, "control_status")).isEqualTo("REVIEW");
            assertThat(selectStatus(connection, "control_controls", 8, "control_status")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "control_controls", 9, "control_status")).isEqualTo("COMPLETED");
            assertThat(selectStatus(connection, "control_controls", 10, "control_status")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "control_controls", 11, "control_status")).isEqualTo("COMPLETED");

            assertThat(selectStatus(connection, "workflow_steps", 1, "status")).isEqualTo("DRAFT");
            assertThat(selectStatus(connection, "workflow_steps", 2, "status")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "workflow_steps", 3, "status")).isEqualTo("REVIEW");
            assertThat(selectStatus(connection, "workflow_steps", 4, "status")).isEqualTo("SOQM_HEAD_REVIEW");
            assertThat(selectStatus(connection, "workflow_steps", 5, "status")).isEqualTo("PROCESS_OWNER_REVIEW");
            assertThat(selectStatus(connection, "workflow_steps", 6, "status")).isEqualTo("COMPLETED");
            assertThat(selectStatus(connection, "workflow_steps", 7, "status")).isEqualTo("COMPLETED");
            assertThat(selectStatus(connection, "workflow_steps", 8, "status")).isEqualTo("COMPLETED");

            assertThat(selectStatus(connection, "workflow_history", 1, "from_step")).isEqualTo("REVIEW");
            assertThat(selectStatus(connection, "workflow_history", 1, "to_step")).isEqualTo("SOQM_HEAD_REVIEW");
            assertThat(selectStatus(connection, "workflow_history", 2, "from_step")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "workflow_history", 2, "to_step")).isEqualTo("IN_PROGRESS");
            assertThat(selectStatus(connection, "workflow_history", 3, "from_step")).isEqualTo("PROCESS_OWNER_REVIEW");
            assertThat(selectStatus(connection, "workflow_history", 3, "to_step")).isEqualTo("COMPLETED");
        }
    }

    private String selectStatus(Connection connection, String table, long id, String column) throws Exception {
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(
                     "SELECT " + column + " FROM " + table + " WHERE id = " + id)) {
            if (!resultSet.next()) {
                return null;
            }
            return resultSet.getString(1);
        }
    }
}

