package com.kpmg.qtracker.migration;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Runs V6-V11 through Flyway on H2 tables shaped like V1 (users with old roles and admin flags, bare controls
 * and workflow_history tables for V7, V9 and V10), then the hand-run undo script of V11.
 */
class V11AdminAccessMigrationTest {

    private static final String UNDO_SCRIPT = "/db/rollback/V11__undo_admin_access_follows_role.sql";

    private String url;
    private Connection connection;

    @BeforeEach
    void setUp() throws Exception {
        url = "jdbc:h2:mem:v11-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        connection = DriverManager.getConnection(url, "sa", "");
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " mail VARCHAR(255) NOT NULL UNIQUE, displayname VARCHAR(255), role VARCHAR(255) NOT NULL,"
                    + " secondary_role VARCHAR(255), enabled BOOLEAN NOT NULL DEFAULT TRUE,"
                    + " admin_access BOOLEAN NOT NULL DEFAULT FALSE, password VARCHAR(255))");
            st.execute("CREATE TABLE controls (id BIGINT PRIMARY KEY, control_id VARCHAR(255))");
            st.execute("CREATE TABLE workflow_history (id BIGINT PRIMARY KEY)");
        }
        // The V2 seed admin: role ADMIN with the flag, which V6 made PARTICIPANT / ALL
        user("admin@x.kz", "ADMIN", true);
        user("soqm-admin@x.kz", "SOQM_TEAM", true);
        user("soqm@x.kz", "SOQM_TEAM", false);
        user("fac-admin@x.kz", "FACILITATOR", true);
        user("ro-admin@x.kz", "Read Only", true);
        user("kdn-admin@x.kz", "KDN", true);
        user("fac@x.kz", "FACILITATOR", false);
    }

    @AfterEach
    void tearDown() throws Exception {
        try (Statement st = connection.createStatement()) {
            st.execute("SHUTDOWN");
        }
        connection.close();
    }

    @Test
    void migrate_flagFollowsTheLevel_andNobodyIsPromoted() throws Exception {
        flyway("10").migrate();
        Map<String, String> levels = levels();

        flyway("11").migrate();

        // Levels and scopes are untouched: the admins without SOQM are not promoted
        assertThat(levels()).isEqualTo(levels);
        assertThat(flags()).containsExactly(
                Map.entry("admin@x.kz", false),
                Map.entry("soqm-admin@x.kz", true),
                Map.entry("soqm@x.kz", true),
                Map.entry("fac-admin@x.kz", false),
                Map.entry("ro-admin@x.kz", false),
                Map.entry("kdn-admin@x.kz", false),
                Map.entry("fac@x.kz", false));
        assertThat(backup()).containsExactly(
                Map.entry("admin@x.kz", true),
                Map.entry("soqm@x.kz", false),
                Map.entry("fac-admin@x.kz", true),
                Map.entry("ro-admin@x.kz", true),
                Map.entry("kdn-admin@x.kz", true));
    }

    @Test
    void afterMigration_theFlagCannotDisagreeWithTheLevel() throws Exception {
        flyway("11").migrate();

        assertRejected("UPDATE users SET admin_access = TRUE WHERE mail = 'fac@x.kz'");
        assertRejected("UPDATE users SET admin_access = FALSE WHERE mail = 'soqm@x.kz'");
        assertRejected("INSERT INTO users (mail, access_level, access_scope, admin_access) VALUES ('a@x.kz', 'SOQM', 'ALL', FALSE)");
        try (Statement st = connection.createStatement()) {
            st.execute("UPDATE users SET access_level = 'SOQM', access_scope = 'ALL', admin_access = TRUE"
                    + " WHERE mail = 'fac@x.kz'");
        }
        assertThat(flags()).containsEntry("fac@x.kz", true);
    }

    @Test
    void undoScript_givesTheOldFlagsBack_unlessTheLevelChangedSince() throws Exception {
        flyway("10").migrate();
        Map<String, Boolean> beforeV11 = flags();
        flyway("11").migrate();
        // Made SoQM Team after V11: that later change is kept
        try (Statement st = connection.createStatement()) {
            st.execute("UPDATE users SET access_level = 'SOQM', access_scope = 'ALL', admin_access = TRUE"
                    + " WHERE mail = 'ro-admin@x.kz'");
        }

        runUndoScript();

        Map<String, Boolean> undone = flags();
        beforeV11.forEach((mail, flag) -> {
            if (!"ro-admin@x.kz".equals(mail)) {
                assertThat(undone.get(mail)).as(mail).isEqualTo(flag);
            }
        });
        assertThat(undone).containsEntry("ro-admin@x.kz", true);
        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM information_schema.tables"
                     + " WHERE LOWER(table_name) = 'user_admin_access_v11_backup'")) {
            rs.next();
            assertThat(rs.getInt(1)).isZero();
        }
        try (Statement st = connection.createStatement()) {
            st.execute("UPDATE users SET admin_access = TRUE WHERE mail = 'fac@x.kz'");
        }
    }

    private void runUndoScript() throws IOException, SQLException {
        String script;
        try (InputStream in = getClass().getResourceAsStream(UNDO_SCRIPT)) {
            assertThat(in).as(UNDO_SCRIPT).isNotNull();
            script = new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
        StringBuilder withoutComments = new StringBuilder();
        for (String line : script.split("\n")) {
            if (!line.trim().startsWith("--")) {
                withoutComments.append(line).append('\n');
            }
        }
        try (Statement st = connection.createStatement()) {
            for (String sql : withoutComments.toString().split(";")) {
                if (!sql.isBlank()) {
                    st.execute(sql);
                }
            }
        }
    }

    private void assertRejected(String sql) {
        assertThatThrownBy(() -> {
            try (Statement st = connection.createStatement()) {
                st.execute(sql);
            }
        }).as(sql).isInstanceOf(SQLException.class);
    }

    private void user(String mail, String role, boolean admin) throws SQLException {
        try (PreparedStatement insert = connection.prepareStatement(
                "INSERT INTO users (mail, role, admin_access) VALUES (?, ?, ?)")) {
            insert.setString(1, mail);
            insert.setString(2, role);
            insert.setBoolean(3, admin);
            insert.executeUpdate();
        }
    }

    /** mail -> "LEVEL/SCOPE". */
    private Map<String, String> levels() throws SQLException {
        Map<String, String> result = new LinkedHashMap<>();
        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT mail, access_level, access_scope FROM users ORDER BY id")) {
            while (rs.next()) {
                result.put(rs.getString(1), rs.getString(2) + "/" + rs.getString(3));
            }
        }
        return result;
    }

    private Map<String, Boolean> flags() throws SQLException {
        return booleans("SELECT mail, admin_access FROM users ORDER BY id");
    }

    private Map<String, Boolean> backup() throws SQLException {
        return booleans("SELECT u.mail, b.admin_access FROM user_admin_access_v11_backup b"
                + " JOIN users u ON u.id = b.user_id ORDER BY u.id");
    }

    private Map<String, Boolean> booleans(String sql) throws SQLException {
        Map<String, Boolean> result = new LinkedHashMap<>();
        try (Statement st = connection.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                result.put(rs.getString(1), rs.getBoolean(2));
            }
        }
        return result;
    }

    /** V1-V4 are PostgreSQL scripts, the tables they produce are created in setUp. */
    private Flyway flyway(String target) {
        return Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("5")
                .target(target)
                .load();
    }
}
