package com.kpmg.qtracker.migration;

import db.migration.V5__Create_control_attachments;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.migration.Context;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Runs V5 through Flyway on an H2 schema shaped like production after V4 (only the columns V5 reads),
 * with data as it occurs there: Cyrillic names, a name listed twice, the same name in both tabs,
 * re-uploads, files without an audit entry and audit rows that are not JSON.
 */
class V5ControlAttachmentsMigrationTest {

    private static final String DETAILS_A = "Отчёт_о_проверке_Q1.pdf";
    private static final String DETAILS_B = "scan (1).png";
    private static final String DOCUMENT = "Политика_контроля.docx";

    private String url;
    private Connection connection;

    @BeforeEach
    void setUp() throws Exception {
        url = "jdbc:h2:mem:v5-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        connection = DriverManager.getConnection(url, "sa", "");
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE TABLE controls (id BIGINT PRIMARY KEY, control_id VARCHAR(255),"
                    + " attachment_details_path TEXT, attachment_documents_path TEXT)");
            st.execute("CREATE TABLE admin_audit_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " control_id BIGINT, created_at TIMESTAMP, action_type VARCHAR(255) NOT NULL,"
                    + " admin_email VARCHAR(255) NOT NULL, changed_fields TEXT, new_values TEXT, previous_values TEXT)");
        }

        // Control 1: a Details name listed twice, the same name also in Documents, one file never audited
        insertControl(1, "HR-01", DETAILS_A + ";" + DETAILS_B + ";" + DETAILS_A + ";", " " + DOCUMENT + " ;" + DETAILS_A);
        // Control 2: no attachments; control 3: only separators
        insertControl(2, "HR-02", null, null);
        insertControl(3, "HR-03", " ; ;", "");

        LocalDateTime t = LocalDateTime.of(2026, 3, 1, 10, 0);
        audit(1, "ATTACHMENT_ADDED", "first@kpmg.kz", "{\"Attachment (DETAILS)\":\"" + DETAILS_A + "\"}", t);
        audit(1, "ATTACHMENT_REMOVED", "first@kpmg.kz", "{}", t.plusDays(1));
        // Re-uploaded later under the same name by someone else: the later uploader is the author
        audit(1, "ATTACHMENT_ADDED", "second@kpmg.kz", "{\"Attachment (DETAILS)\":\"" + DETAILS_A + "\"}", t.plusDays(2));
        audit(1, "ATTACHMENT_ADDED", "docs@kpmg.kz", "{\"Attachment (DOCUMENTS)\":\"" + DOCUMENT + "\"}", t.plusDays(3));
        audit(1, "ATTACHMENT_ADDED", "broken@kpmg.kz", "not json at all", t.plusDays(4));
        audit(1, "EDIT", "editor@kpmg.kz", "Component: HR -> GOV", t.plusDays(5));
    }

    @AfterEach
    void tearDown() throws Exception {
        try (Statement st = connection.createStatement()) {
            st.execute("SHUTDOWN");
        }
        connection.close();
    }

    @Test
    void migrate_createsOneRowPerListedFile_withAuthorFromAuditLog() throws Exception {
        MigrateResult result = flyway().migrate();

        assertThat(result.migrationsExecuted).isEqualTo(1);
        List<String> rows = rows();
        assertThat(rows).containsExactlyInAnyOrder(
                "1|DETAILS|" + DETAILS_A + "|second@kpmg.kz|null|2026-03-03 10:00:00.0",
                "1|DETAILS|" + DETAILS_B + "|null|null|null",
                "1|DOCUMENTS|" + DETAILS_A + "|null|null|null",
                "1|DOCUMENTS|" + DOCUMENT + "|docs@kpmg.kz|null|2026-03-04 10:00:00.0");
    }

    @Test
    void migrate_leavesAttachmentListsUnchanged() throws Exception {
        flyway().migrate();

        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT id, attachment_details_path, attachment_documents_path FROM controls ORDER BY id")) {
            rs.next();
            assertThat(rs.getString(2)).isEqualTo(DETAILS_A + ";" + DETAILS_B + ";" + DETAILS_A + ";");
            assertThat(rs.getString(3)).isEqualTo(" " + DOCUMENT + " ;" + DETAILS_A);
            rs.next();
            assertThat(rs.getString(2)).isNull();
            rs.next();
            assertThat(rs.getString(2)).isEqualTo(" ; ;");
        }
    }

    @Test
    void migrate_runAgain_addsOnlyNewFilesAndKeepsExistingRows() throws Exception {
        flyway().migrate();
        // A file uploaded after V5 already has its own row with author and stage
        try (Statement st = connection.createStatement()) {
            st.execute("UPDATE controls SET attachment_details_path = attachment_details_path || 'new.pdf' WHERE id = 1");
            st.execute("INSERT INTO control_attachments (control_id, tab, file_name, uploaded_by_email, uploaded_stage)"
                    + " VALUES (1, 'DETAILS', 'new.pdf', 'fac@kpmg.kz', 'IN_PROGRESS')");
            st.execute("UPDATE controls SET attachment_documents_path = 'later.xlsx' WHERE id = 2");
        }

        Context context = mock(Context.class);
        when(context.getConnection()).thenReturn(connection);
        new V5__Create_control_attachments().migrate(context);

        assertThat(rows()).containsExactlyInAnyOrder(
                "1|DETAILS|" + DETAILS_A + "|second@kpmg.kz|null|2026-03-03 10:00:00.0",
                "1|DETAILS|" + DETAILS_B + "|null|null|null",
                "1|DETAILS|new.pdf|fac@kpmg.kz|IN_PROGRESS|null",
                "1|DOCUMENTS|" + DETAILS_A + "|null|null|null",
                "1|DOCUMENTS|" + DOCUMENT + "|docs@kpmg.kz|null|2026-03-04 10:00:00.0",
                "2|DOCUMENTS|later.xlsx|null|null|null");
    }

    @Test
    void deletingControl_removesItsAttachmentRows() throws Exception {
        flyway().migrate();

        try (Statement st = connection.createStatement()) {
            st.execute("DELETE FROM controls WHERE id = 1");
        }

        assertThat(rows()).isEmpty();
    }

    /** Applies only V5: V1-V4 are PostgreSQL scripts, the schema they produce is created in setUp. */
    private Flyway flyway() {
        return Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("4")
                .load();
    }

    private List<String> rows() throws Exception {
        List<String> rows = new ArrayList<>();
        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT control_id, tab, file_name, uploaded_by_email, uploaded_stage, uploaded_at"
                     + " FROM control_attachments ORDER BY control_id, tab, file_name")) {
            while (rs.next()) {
                rows.add(rs.getLong(1) + "|" + rs.getString(2) + "|" + rs.getString(3) + "|" + rs.getString(4)
                        + "|" + rs.getString(5) + "|" + rs.getTimestamp(6));
            }
        }
        return rows;
    }

    private void insertControl(long id, String controlId, String details, String documents) throws Exception {
        try (PreparedStatement ps = connection.prepareStatement(
                "INSERT INTO controls (id, control_id, attachment_details_path, attachment_documents_path) VALUES (?, ?, ?, ?)")) {
            ps.setLong(1, id);
            ps.setString(2, controlId);
            ps.setString(3, details);
            ps.setString(4, documents);
            ps.executeUpdate();
        }
    }

    private void audit(long controlId, String action, String email, String newValues, LocalDateTime at) throws Exception {
        try (PreparedStatement ps = connection.prepareStatement(
                "INSERT INTO admin_audit_log (control_id, created_at, action_type, admin_email, new_values) VALUES (?, ?, ?, ?, ?)")) {
            ps.setLong(1, controlId);
            ps.setTimestamp(2, Timestamp.valueOf(at));
            ps.setString(3, action);
            ps.setString(4, email);
            ps.setString(5, newValues);
            ps.executeUpdate();
        }
    }
}
