package com.kpmg.qtracker.migration;

import com.kpmg.qtracker.service.LegacyRoleAccess;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.output.MigrateResult;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Runs V6 through Flyway on an H2 users table shaped like V1, with the role values that occur in the
 * databases (normalized and not, both role columns, the seed ADMIN string, values the code never knew).
 */
class V6UserAccessMigrationTest {

    private String url;
    private Connection connection;

    /** mail -> role, secondary_role, admin_access */
    private final Map<String, String[]> users = new LinkedHashMap<>();

    @BeforeEach
    void setUp() throws Exception {
        url = "jdbc:h2:mem:v6-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        connection = DriverManager.getConnection(url, "sa", "");
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " mail VARCHAR(255) NOT NULL UNIQUE, displayname VARCHAR(255), role VARCHAR(255) NOT NULL,"
                    + " secondary_role VARCHAR(255), enabled BOOLEAN NOT NULL DEFAULT TRUE,"
                    + " admin_access BOOLEAN NOT NULL DEFAULT FALSE, password VARCHAR(255))");
        }
        user("soqm@x.kz", "SOQM_TEAM", null, false);
        user("soqm-label@x.kz", " SoQM Team ", null, false);
        user("soqm-head@x.kz", "soqm-head", null, false);
        user("fac@x.kz", "FACILITATOR", null, false);
        user("op@x.kz", "Control Operator", "FACILITATOR", false);
        user("po@x.kz", "PROCESS_OWNER", null, true);
        user("kdn@x.kz", "KDN", "FACILITATOR", false);
        user("kdn-second@x.kz", "FACILITATOR", "kdn", false);
        user("soqm-kdn@x.kz", "SOQM_TEAM", "KDN", false);
        user("admin@x.kz", "ADMIN", null, true);
        user("admin-no-flag@x.kz", "admin", null, false);
        user("master@x.kz", "Master", null, false);
        user("readonly@x.kz", "Read Only", null, false);
        user("unknown@x.kz", "AUDITOR", null, false);
        user("blank@x.kz", "", null, false);
    }

    @AfterEach
    void tearDown() throws Exception {
        try (Statement st = connection.createStatement()) {
            st.execute("SHUTDOWN");
        }
        connection.close();
    }

    @Test
    void migrate_mapsEveryOldRole() throws Exception {
        MigrateResult result = flyway().migrate();

        assertThat(result.migrationsExecuted).isEqualTo(1);
        assertThat(access()).containsExactly(
                Map.entry("soqm@x.kz", "SOQM/ALL/false"),
                Map.entry("soqm-label@x.kz", "SOQM/ALL/false"),
                Map.entry("soqm-head@x.kz", "SOQM/ALL/false"),
                Map.entry("fac@x.kz", "PARTICIPANT/OWN/false"),
                Map.entry("op@x.kz", "PARTICIPANT/OWN/false"),
                Map.entry("po@x.kz", "PARTICIPANT/OWN/true"),
                Map.entry("kdn@x.kz", "PARTICIPANT/KDN/false"),
                Map.entry("kdn-second@x.kz", "PARTICIPANT/KDN/false"),
                // KDN used to restrict even a SoQM role to viewing KDN controls
                Map.entry("soqm-kdn@x.kz", "PARTICIPANT/KDN/false"),
                Map.entry("admin@x.kz", "PARTICIPANT/ALL/true"),
                Map.entry("admin-no-flag@x.kz", "PARTICIPANT/ALL/false"),
                Map.entry("master@x.kz", "PARTICIPANT/ALL/false"),
                Map.entry("readonly@x.kz", "READ_ONLY/OWN/false"),
                Map.entry("unknown@x.kz", "READ_ONLY/OWN/false"),
                Map.entry("blank@x.kz", "READ_ONLY/OWN/false"));
    }

    @Test
    void migrate_keepsTheOldRoleColumns() throws Exception {
        flyway().migrate();

        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT role, secondary_role FROM users WHERE mail = 'soqm-kdn@x.kz'")) {
            rs.next();
            assertThat(rs.getString(1)).isEqualTo("SOQM_TEAM");
            assertThat(rs.getString(2)).isEqualTo("KDN");
        }
    }

    @Test
    void javaMapping_matchesTheBackfill() throws Exception {
        flyway().migrate();

        Map<String, String> migrated = access();
        users.forEach((mail, values) -> {
            LegacyRoleAccess.Access access = LegacyRoleAccess.of(values[0], values[1]);
            assertThat(migrated.get(mail))
                    .as(mail)
                    .startsWith(access.level() + "/" + access.scope() + "/");
        });
    }

    @Test
    void afterMigration_newUsersNeedNoRole_andGetTheLeastAccessByDefault() throws Exception {
        flyway().migrate();

        try (Statement st = connection.createStatement()) {
            st.execute("INSERT INTO users (mail) VALUES ('new@x.kz')");
        }
        assertThat(access()).containsEntry("new@x.kz", "READ_ONLY/OWN/false");
    }

    @Test
    void afterMigration_checksRejectUnknownValuesAndSoqmOutsideScopeAll() throws Exception {
        flyway().migrate();

        assertRejected("INSERT INTO users (mail, access_level, access_scope) VALUES ('a@x.kz', 'ADMIN', 'OWN')");
        assertRejected("INSERT INTO users (mail, access_level, access_scope) VALUES ('b@x.kz', 'PARTICIPANT', 'MINE')");
        assertRejected("INSERT INTO users (mail, access_level, access_scope) VALUES ('c@x.kz', 'SOQM', 'OWN')");
        assertRejected("INSERT INTO users (mail, access_level, access_scope) VALUES ('d@x.kz', 'SOQM', 'KDN')");
        assertRejected("UPDATE users SET access_level = NULL WHERE mail = 'fac@x.kz'");

        try (Statement st = connection.createStatement()) {
            st.execute("INSERT INTO users (mail, access_level, access_scope) VALUES ('e@x.kz', 'READ_ONLY', 'ALL')");
            st.execute("INSERT INTO users (mail, access_level, access_scope) VALUES ('f@x.kz', 'SOQM', 'ALL')");
        }
        assertThat(access()).containsEntry("e@x.kz", "READ_ONLY/ALL/false").containsEntry("f@x.kz", "SOQM/ALL/false");
    }

    private void assertRejected(String sql) {
        assertThatThrownBy(() -> {
            try (Statement st = connection.createStatement()) {
                st.execute(sql);
            }
        }).as(sql).isInstanceOf(SQLException.class);
    }

    private void user(String mail, String role, String secondaryRole, boolean admin) throws SQLException {
        users.put(mail, new String[]{role, secondaryRole});
        try (PreparedStatement insert = connection.prepareStatement(
                "INSERT INTO users (mail, role, secondary_role, admin_access) VALUES (?, ?, ?, ?)")) {
            insert.setString(1, mail);
            insert.setString(2, role);
            insert.setString(3, secondaryRole);
            insert.setBoolean(4, admin);
            insert.executeUpdate();
        }
    }

    /** mail -> "LEVEL/SCOPE/admin", in insertion order. */
    private Map<String, String> access() throws SQLException {
        Map<String, String> result = new LinkedHashMap<>();
        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT mail, access_level, access_scope, admin_access FROM users ORDER BY id")) {
            while (rs.next()) {
                result.put(rs.getString(1), rs.getString(2) + "/" + rs.getString(3) + "/" + rs.getBoolean(4));
            }
        }
        return result;
    }

    /** Applies only V6: V1-V4 are PostgreSQL scripts, the users table they produce is created in setUp. */
    private Flyway flyway() {
        return Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("5")
                .target("6")
                .load();
    }
}
