package com.kpmg.qtracker.migration;

import com.kpmg.qtracker.service.LegacyRoleAccess;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Runs V6-V8 through Flyway on H2 tables shaped like V1 (users with old roles, a bare controls table for V7),
 * then the hand-run undo script db/rollback/V8__undo_KDN_users_read_only.sql.
 */
class V8KdnReadOnlyMigrationTest {

    private static final String UNDO_SCRIPT = "/db/rollback/V8__undo_KDN_users_read_only.sql";

    private String url;
    private Connection connection;

    /** mail -> role, secondary_role */
    private final Map<String, String[]> users = new LinkedHashMap<>();

    @BeforeEach
    void setUp() throws Exception {
        url = "jdbc:h2:mem:v8-" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        connection = DriverManager.getConnection(url, "sa", "");
        try (Statement st = connection.createStatement()) {
            st.execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " mail VARCHAR(255) NOT NULL UNIQUE, displayname VARCHAR(255), role VARCHAR(255) NOT NULL,"
                    + " secondary_role VARCHAR(255), enabled BOOLEAN NOT NULL DEFAULT TRUE,"
                    + " admin_access BOOLEAN NOT NULL DEFAULT FALSE, password VARCHAR(255))");
            st.execute("CREATE TABLE controls (id BIGINT PRIMARY KEY, control_id VARCHAR(255))");
        }
        user("kdn@x.kz", "KDN", "FACILITATOR");
        user("kdn-second@x.kz", "FACILITATOR", "kdn");
        user("soqm-kdn@x.kz", "SOQM_TEAM", "KDN");
        user("soqm@x.kz", "SOQM_TEAM", null);
        user("fac@x.kz", "FACILITATOR", null);
        user("master@x.kz", "Master", null);
        user("readonly@x.kz", "Read Only", null);
    }

    @AfterEach
    void tearDown() throws Exception {
        try (Statement st = connection.createStatement()) {
            st.execute("SHUTDOWN");
        }
        connection.close();
    }

    @Test
    void migrate_makesKdnUsersReadOnly_andTouchesNobodyElse() throws Exception {
        flyway("6").migrate();
        Map<String, String> before = access();
        // Made READ_ONLY / KDN by hand before V8: nothing to change, nothing to keep
        insertUser("ro-kdn@x.kz", "READ_ONLY", "KDN");

        flyway("8").migrate();

        Map<String, String> after = access();
        assertThat(after).containsEntry("kdn@x.kz", "READ_ONLY/KDN")
                .containsEntry("kdn-second@x.kz", "READ_ONLY/KDN")
                .containsEntry("soqm-kdn@x.kz", "READ_ONLY/KDN")
                .containsEntry("ro-kdn@x.kz", "READ_ONLY/KDN");
        before.forEach((mail, value) -> {
            if (!value.endsWith("/KDN")) {
                assertThat(after.get(mail)).as(mail).isEqualTo(value);
            }
        });
        assertThat(backup()).containsExactly(
                Map.entry("kdn@x.kz", "PARTICIPANT/KDN"),
                Map.entry("kdn-second@x.kz", "PARTICIPANT/KDN"),
                Map.entry("soqm-kdn@x.kz", "PARTICIPANT/KDN"));
    }

    @Test
    void afterMigration_scopeKdnGoesOnlyWithReadOnly() throws Exception {
        flyway("8").migrate();

        assertRejected("INSERT INTO users (mail, access_level, access_scope) VALUES ('a@x.kz', 'PARTICIPANT', 'KDN')");
        assertRejected("UPDATE users SET access_level = 'PARTICIPANT' WHERE mail = 'kdn@x.kz'");
        insertUser("b@x.kz", "READ_ONLY", "KDN");
        assertThat(access()).containsEntry("b@x.kz", "READ_ONLY/KDN");
    }

    @Test
    void javaMapping_matchesTheMigratedDatabase() throws Exception {
        flyway("8").migrate();

        Map<String, String> migrated = access();
        users.forEach((mail, values) -> {
            LegacyRoleAccess.Access access = LegacyRoleAccess.of(values[0], values[1]);
            assertThat(migrated.get(mail)).as(mail).isEqualTo(access.level() + "/" + access.scope());
        });
    }

    @Test
    void undoScript_givesTheMigratedUsersTheirOldLevelBack() throws Exception {
        flyway("6").migrate();
        insertUser("ro-kdn@x.kz", "READ_ONLY", "KDN");
        Map<String, String> beforeV8 = access();
        flyway("8").migrate();
        // Changed by an admin after V8: that later change is kept
        try (Statement st = connection.createStatement()) {
            st.execute("UPDATE users SET access_scope = 'OWN' WHERE mail = 'kdn-second@x.kz'");
        }

        runUndoScript();

        Map<String, String> undone = access();
        beforeV8.forEach((mail, value) -> {
            if (!"kdn-second@x.kz".equals(mail)) {
                assertThat(undone.get(mail)).as(mail).isEqualTo(value);
            }
        });
        assertThat(undone).containsEntry("kdn-second@x.kz", "READ_ONLY/OWN");
        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM information_schema.tables"
                     + " WHERE LOWER(table_name) = 'user_access_v8_backup'")) {
            rs.next();
            assertThat(rs.getInt(1)).isZero();
        }
        insertUser("participant-kdn@x.kz", "PARTICIPANT", "KDN");
    }

    private void runUndoScript() throws IOException, SQLException {
        String script;
        try (InputStream in = getClass().getResourceAsStream(UNDO_SCRIPT)) {
            assertThat(in).as(UNDO_SCRIPT).isNotNull();
            script = new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
        StringBuilder withoutComments = new StringBuilder();
        for (String line : script.split("\n")) {
            if (!line.trim().startsWith("--")) {
                withoutComments.append(line).append('\n');
            }
        }
        try (Statement st = connection.createStatement()) {
            for (String sql : withoutComments.toString().split(";")) {
                if (!sql.isBlank()) {
                    st.execute(sql);
                }
            }
        }
    }

    private void assertRejected(String sql) {
        assertThatThrownBy(() -> {
            try (Statement st = connection.createStatement()) {
                st.execute(sql);
            }
        }).as(sql).isInstanceOf(SQLException.class);
    }

    private void user(String mail, String role, String secondaryRole) throws SQLException {
        users.put(mail, new String[]{role, secondaryRole});
        try (PreparedStatement insert = connection.prepareStatement(
                "INSERT INTO users (mail, role, secondary_role) VALUES (?, ?, ?)")) {
            insert.setString(1, mail);
            insert.setString(2, role);
            insert.setString(3, secondaryRole);
            insert.executeUpdate();
        }
    }

    private void insertUser(String mail, String level, String scope) throws SQLException {
        try (PreparedStatement insert = connection.prepareStatement(
                "INSERT INTO users (mail, access_level, access_scope) VALUES (?, ?, ?)")) {
            insert.setString(1, mail);
            insert.setString(2, level);
            insert.setString(3, scope);
            insert.executeUpdate();
        }
    }

    /** mail -> "LEVEL/SCOPE", in insertion order. */
    private Map<String, String> access() throws SQLException {
        return pairs("SELECT mail, access_level, access_scope FROM users ORDER BY id");
    }

    private Map<String, String> backup() throws SQLException {
        return pairs("SELECT u.mail, b.access_level, b.access_scope FROM user_access_v8_backup b"
                + " JOIN users u ON u.id = b.user_id ORDER BY u.id");
    }

    private Map<String, String> pairs(String sql) throws SQLException {
        Map<String, String> result = new LinkedHashMap<>();
        try (Statement st = connection.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                result.put(rs.getString(1), rs.getString(2) + "/" + rs.getString(3));
            }
        }
        return result;
    }

    /** V1-V4 are PostgreSQL scripts, the tables they produce are created in setUp. */
    private Flyway flyway(String target) {
        return Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("5")
                .target(target)
                .load();
    }
}
