package db.migration;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

/**
 * Creates control_attachments (who uploaded a file and in which stage) and adds a row for every file
 * already listed in controls.attachment_details_path / attachment_documents_path.
 * <p>
 * The author comes from the latest ATTACHMENT_ADDED entry in admin_audit_log for that control, tab
 * and file name, or stays empty; the stage of old uploads is unknown and stays empty, so only SoQM
 * Team may delete those files. The attachment_*_path columns are only read. Written in Java rather
 * than SQL so the same code runs on PostgreSQL and on the H2 database of the tests, and safe to
 * re-run: existing rows and repeated names are skipped.
 */
public class V5__Create_control_attachments extends BaseJavaMigration {

    private static final String DETAILS = "DETAILS";
    private static final String DOCUMENTS = "DOCUMENTS";

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        createTable(connection);

        Set<String> existing = loadExistingKeys(connection);
        Map<String, Upload> uploads = loadUploadsFromAuditLog(connection);

        try (Statement select = connection.createStatement();
             ResultSet controls = select.executeQuery(
                     "SELECT id, attachment_details_path, attachment_documents_path FROM controls");
             PreparedStatement insert = connection.prepareStatement(
                     "INSERT INTO control_attachments (control_id, tab, file_name, uploaded_by_email, uploaded_at)"
                             + " VALUES (?, ?, ?, ?, ?)")) {
            int pending = 0;
            while (controls.next()) {
                long controlId = controls.getLong("id");
                pending += addRows(insert, existing, uploads, controlId, DETAILS, controls.getString("attachment_details_path"));
                pending += addRows(insert, existing, uploads, controlId, DOCUMENTS, controls.getString("attachment_documents_path"));
            }
            if (pending > 0) {
                insert.executeBatch();
            }
        }
    }

    private void createTable(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE IF NOT EXISTS control_attachments ("
                    + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + " control_id BIGINT NOT NULL REFERENCES controls(id) ON DELETE CASCADE,"
                    + " tab VARCHAR(20) NOT NULL,"
                    + " file_name VARCHAR(1000) NOT NULL,"
                    + " uploaded_by_email VARCHAR(255),"
                    + " uploaded_stage VARCHAR(50),"
                    + " uploaded_at TIMESTAMP,"
                    + " CONSTRAINT uq_control_attachments_file UNIQUE (control_id, tab, file_name))");
        }
    }

    private int addRows(PreparedStatement insert, Set<String> existing, Map<String, Upload> uploads,
                        long controlId, String tab, String storedList) throws SQLException {
        if (storedList == null || storedList.isBlank()) {
            return 0;
        }
        // The same name may be listed twice; one row per name
        Set<String> names = new LinkedHashSet<>();
        for (String part : storedList.split(";")) {
            String name = part.trim();
            if (!name.isEmpty()) {
                names.add(name);
            }
        }
        int added = 0;
        for (String name : names) {
            String key = key(controlId, tab, name);
            if (!existing.add(key)) {
                continue;
            }
            Upload upload = uploads.get(key);
            insert.setLong(1, controlId);
            insert.setString(2, tab);
            insert.setString(3, name);
            insert.setString(4, upload != null ? upload.email : null);
            insert.setTimestamp(5, upload != null ? upload.at : null);
            insert.addBatch();
            added++;
        }
        return added;
    }

    private Set<String> loadExistingKeys(Connection connection) throws SQLException {
        Set<String> keys = new HashSet<>();
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery("SELECT control_id, tab, file_name FROM control_attachments")) {
            while (rows.next()) {
                keys.add(key(rows.getLong("control_id"), rows.getString("tab"), rows.getString("file_name")));
            }
        }
        return keys;
    }

    /**
     * Latest uploader per control, tab and file name. FileAttachmentController logs each added file as
     * new_values = {"Attachment (DETAILS)": "name"}; entries that cannot be read are skipped.
     */
    private Map<String, Upload> loadUploadsFromAuditLog(Connection connection) throws SQLException {
        Map<String, Upload> uploads = new HashMap<>();
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery(
                     "SELECT control_id, admin_email, new_values, created_at FROM admin_audit_log"
                             + " WHERE action_type = 'ATTACHMENT_ADDED' AND control_id IS NOT NULL"
                             + " ORDER BY created_at, id")) {
            while (rows.next()) {
                long controlId = rows.getLong("control_id");
                String email = rows.getString("admin_email");
                Timestamp at = rows.getTimestamp("created_at");
                JsonNode values = parse(rows.getString("new_values"));
                if (values == null) {
                    continue;
                }
                for (String tab : new String[]{DETAILS, DOCUMENTS}) {
                    JsonNode name = values.get("Attachment (" + tab + ")");
                    if (name != null && name.isTextual() && !name.asText().isBlank()) {
                        // Ordered by time, so a later upload of the same name wins
                        uploads.put(key(controlId, tab, name.asText().trim()), new Upload(email, at));
                    }
                }
            }
        }
        return uploads;
    }

    private JsonNode parse(String json) {
        if (json == null || json.isBlank()) {
            return null;
        }
        try {
            JsonNode node = objectMapper.readTree(json);
            return node != null && node.isObject() ? node : null;
        } catch (Exception e) {
            return null;
        }
    }

    private static String key(long controlId, String tab, String fileName) {
        return controlId + "\u0000" + tab + "\u0000" + fileName;
    }

    private record Upload(String email, Timestamp at) {
    }
}
